# Generated by Django 2.1 on 2019-06-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('criticality', models.CharField(choices=[(1, 'High'), (2, 'Low'), (3, 'Avarage')], max_length=100)),
                ('status', models.CharField(choices=[(1, 'Completed'), (2, 'Work in Progress'), (3, 'Not Started')], max_length=100)),
            ],
        ),
    ]
