# Generated by Django 2.1 on 2020-01-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_auto_20200124_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='due_date',
            field=models.CharField(max_length=100),
        ),
    ]
