# Generated by Django 2.1 on 2020-02-02 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0003_auto_20200124_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
