# Generated by Django 2.1 on 2020-02-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0004_auto_20200202_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
